pipeline {
    agent any
    
    tools {
        jdk 'JAVA11'
        maven 'mv392'
    }

    environment{
        REGISTRYLOCATION = "https://www.google.com/"
    }
    
     stages {
           stage('Initialize'){
            steps{
                script{
                        echo "Inicializando"
                        sh 'java --version'
                        sh "mvn -version"
                    }
                }
             }
             stage('Resolver dependencias'){
            steps{
                script{
                        dir("cursomaven\EjemploMaven/"){
                            echo "Generando dependencias"
                            sh 'mvn dependency:resolve'
                            sh 'mvn package'
                            sh 'mvn install'
                            
                            
                            
                        }
                        
                    }
                }
             }
            stage('generar documentacion'){
            steps{
                script{
                        dir("cursomaven\EjemploMaven2/"){
                            echo "Generando documentacion"
                            sh 'mvn dependency:resolve'
                            sh 'mvn pmd:pmd'
                            sh 'mvn checkstyle:checkstyle'
                            sh 'mvn javadoc:javadoc'
                            sh 'mvn site:site'
                            
                            
                        }
                        
                    }
                }
             }
     }
    
} 